package livefootball.footballstreamning.fifaworldcup.network

import livefootball.footballstreamning.fifaworldcup.models.ApiResponse
import retrofit2.http.GET
import retrofit2.http.Header

interface ApiService {
    @GET("https://db.thebicodes.com/items/apps?fields=*,ads.*,streaming.*,streaming.streaming_id.*,streaming.streaming_id.tournaments.*,streaming.streaming_id.tournaments.tournaments_id.*,streaming.streaming_id.tournaments.tournaments_id.events.*,streaming.streaming_id.tournaments.tournaments_id.events.events_id.*,streaming.streaming_id.tournaments.tournaments_id.events.events_id.highligths.*,streaming.streaming_id.tournaments.tournaments_id.events.events_id.highligths.highlights_id.*,streaming.streaming_id.tournaments.tournaments_id.events.events_id.links.*,streaming.streaming_id.tournaments.tournaments_id.events.events_id.links.links_id.*&filter%5B_and%5D%5B0%5D%5Bid%5D%5B_eq%5D=16&filter%5B_and%5D%5B1%5D%5Bis_active%5D%5B_eq%5D=true&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5B_filter%5D%5B_and%5D%5B0%5D%5Btournaments_id%5D%5Bis_visible%5D%5B_eq%5D=true&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5B_filter%5D%5B_and%5D%5B1%5D%5B_or%5D%5B0%5D%5Btournaments_id%5D%5Bexcluded_app_package_names%5D%5B_null%5D=true&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5B_filter%5D%5B_and%5D%5B1%5D%5B_or%5D%5B1%5D%5Btournaments_id%5D%5Bexcluded_app_package_names%5D%5B_ncontains%5D=livefootball.footballstreamning.fifaworldcup&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5Btournaments_id%5D%5Bevents%5D%5B_filter%5D%5B_and%5D%5B0%5D%5Bevents_id%5D%5Bis_visible%5D%5B_eq%5D=true&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5Btournaments_id%5D%5Bevents%5D%5B_filter%5D%5B_and%5D%5B1%5D%5B_or%5D%5B0%5D%5Bevents_id%5D%5Bexcluded_app_package_names%5D%5B_null%5D=true&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5Btournaments_id%5D%5Bevents%5D%5B_filter%5D%5B_and%5D%5B1%5D%5B_or%5D%5B1%5D%5Bevents_id%5D%5Bexcluded_app_package_names%5D%5B_ncontains%5D=livefootball.footballstreamning.fifaworldcup&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5Btournaments_id%5D%5Bevents%5D%5Bevents_id%5D%5Blinks%5D%5B_filter%5D%5B_and%5D%5B0%5D%5Blinks_id%5D%5Bis_visible%5D%5B_eq%5D=true&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5Btournaments_id%5D%5Bevents%5D%5Bevents_id%5D%5Blinks%5D%5B_filter%5D%5B_and%5D%5B1%5D%5B_or%5D%5B0%5D%5Blinks_id%5D%5Bexcluded_app_package_names%5D%5B_null%5D=true&deep%5Bstreaming%5D%5Bstreaming_id%5D%5Btournaments%5D%5Btournaments_id%5D%5Bevents%5D%5Bevents_id%5D%5Blinks%5D%5B_filter%5D%5B_and%5D%5B1%5D%5B_or%5D%5B1%5D%5Blinks_id%5D%5Bexcluded_app_package_names%5D%5B_ncontains%5D=livefootball.footballstreamning.fifaworldcup")
    suspend fun getAppConfig(
        @Header("Authorization") token: String
    ): ApiResponse
}
